theme: jekyll-theme-architect
title: Coder un jeu simple en 2D avec HTML et Javascript au collège
description : Un petit tuto adapté aux élèves de 6ème pour aller plus loin qu'avec Scratch et apprendre à coder soi même un petit jeu de A à Z pour occuper ses parents quand ils s'ennuient sur leur téléphone dans le bus qui les emmène au travail :-)


